
import sqlite3

import config

# database name to be passed as parameter 
conn = sqlite3.connect(config.DB_NAME)

conn.execute("insert into records (artist_name, album_name) values('All Tiny Creatures','Harbors')")
conn.execute("insert into records (artist_name, album_name) values('All Tiny Creatures','Dark Clock')")
conn.execute("insert into records (artist_name, album_name) values('The American Analog Set','Know By Heart')")
conn.execute("insert into records (artist_name, album_name) values('...And You Will Know Us by the Trail of Dead','Madonna')")
conn.execute("insert into records (artist_name, album_name) values('...And You Will Know Us by the Trail of Dead','Source Tags & Codes')")
conn.execute("insert into records (artist_name, album_name) values('The Appleseed Cast','Low Level Owl: Volumes I + II')")
conn.execute("insert into records (artist_name, album_name) values('The Appleseed Cast','Peregrine')")
conn.execute("insert into records (artist_name, album_name) values('Arcade Fire','Cold Wind')")
conn.execute("insert into records (artist_name, album_name) values('Arcade Fire','Rebellion (Lies)')")
conn.execute("insert into records (artist_name, album_name) values('Arcade Fire','Wake Up')")
conn.execute("insert into records (artist_name, album_name) values('Arcade Fire','Keep the Car Running')")
conn.execute("insert into records (artist_name, album_name) values('Atelje','Meditation')")
conn.execute("insert into records (artist_name, album_name) values('Atelje','50/50')")
conn.execute("insert into records (artist_name, album_name) values('Bell Orchestre','As Seen Through Windows')")
conn.execute("insert into records (artist_name, album_name) values('Ben Harper and the Blind Boys of Alabama','Ther Will Be a Light')")
conn.execute("insert into records (artist_name, album_name) values('Bob Dylan','Desire')")
conn.execute("insert into records (artist_name, album_name) values('Bonobo','Black Sands')")
conn.execute("insert into records (artist_name, album_name) values('Boris','Smile')")
conn.execute("insert into records (artist_name, album_name) values('Boy in Static','Violet')")
conn.execute("insert into records (artist_name, album_name) values('Broken Social Scene','Broken Social Scene')")
conn.execute("insert into records (artist_name, album_name) values('Broken Social Scene','Forgiveness Rock Record')")
conn.execute("insert into records (artist_name, album_name) values('Camel Heads','Anoluz')")
conn.execute("insert into records (artist_name, album_name) values('Canyons of Static','Northern Highland')")
conn.execute("insert into records (artist_name, album_name) values('Canyons of Static/Glowfriends','The Calm')")
conn.execute("insert into records (artist_name, album_name) values('Canyons of Static','Wake/Drift')")
conn.execute("insert into records (artist_name, album_name) values('Caspian','Dust and Disquiet')")
conn.execute("insert into records (artist_name, album_name) values('Caveman','Caveman')")
conn.execute("insert into records (artist_name, album_name) values('Chelsea Light Moving','Chelsea Light Moving')")
conn.execute("insert into records (artist_name, album_name) values('Colin Stetson and Sarah Neufeld','Never Were the Way She Was')")
conn.execute("insert into records (artist_name, album_name) values('Collections of Colonies of Bees','Birds')")
conn.execute("insert into records (artist_name, album_name) values('Collections of Colonies of Bees','Giving')")
conn.execute("insert into records (artist_name, album_name) values('Collections of Colonies of Bees','Hawaii')")
conn.execute("insert into records (artist_name, album_name) values('D. Lissvik','7 Trx + Intermission')")
conn.execute("insert into records (artist_name, album_name) values('Dakota/Dakota/Riddle of Steel','It''s Not a Mustache, It''s a Mouthbrow/Our Guitars Are Haunted')")
conn.execute("insert into records (artist_name, album_name) values('Dan Lissvik','Shuvit!')")
conn.execute("insert into records (artist_name, album_name) values('Dan Lissvik','Midnight')")
conn.execute("insert into records (artist_name, album_name) values('Death Blues','Non-Fiction')")
conn.execute("insert into records (artist_name, album_name) values('Death Blues','Ensemble')")
conn.execute("insert into records (artist_name, album_name) values('Death Cab for Cutie','Transatlanticism')")
conn.execute("insert into records (artist_name, album_name) values('Death Cab for Cutie','Soul Meets Body')")
conn.execute("insert into records (artist_name, album_name) values('Dirty Three','Cinder')")
conn.execute("insert into records (artist_name, album_name) values('DJ Jazzy Jeff & The Fresh Prince','He''s the DJ, I''m the Rapper')")
conn.execute("insert into records (artist_name, album_name) values('Do Make Say Think','You, You''re a History in Rust')")
conn.execute("insert into records (artist_name, album_name) values('Don Caballero','For Respect')")
conn.execute("insert into records (artist_name, album_name) values('Earth','The Bees Made Honey in the Lion''s Skull')")
conn.execute("insert into records (artist_name, album_name) values('Efrim Menuck','Plays ""High Gospel""')")
conn.execute("insert into records (artist_name, album_name) values('Elliott Smith','XO')")
conn.execute("insert into records (artist_name, album_name) values('Emeralds','Just to Feel Anything')")
conn.execute("insert into records (artist_name, album_name) values('Esmerine','If Only a Sweet Surrender to the Nights to Come Be True')")
conn.execute("insert into records (artist_name, album_name) values('Esmerine','Aurora')")
conn.execute("insert into records (artist_name, album_name) values('Esmerine','La Lechuza')")
conn.execute("insert into records (artist_name, album_name) values('Esmerine','Dalmak')")
conn.execute("insert into records (artist_name, album_name) values('Esmerine','Lost Voices')")
conn.execute("insert into records (artist_name, album_name) values('Esmerine','Mechanics of Dominion')")
conn.execute("insert into records (artist_name, album_name) values('Explosions in the Sky','Those Who Tell the Truth Shall Die, Those Who Tell the Truth Shall Live Forever')")
conn.execute("insert into records (artist_name, album_name) values('Explosions in the Sky','The Earth Is Not a Cold Dead Place')")
conn.execute("insert into records (artist_name, album_name) values('Explosions in the Sky','The Rescue')")
conn.execute("insert into records (artist_name, album_name) values('Explosions in the Sky','Take Care, Take Care, Take Care')")
conn.execute("insert into records (artist_name, album_name) values('Explosions in the Sky','Prince Avalanche Soundtrack')")
conn.execute("insert into records (artist_name, album_name) values('Fletcher Tucker','Cold Spring')")
conn.execute("insert into records (artist_name, album_name) values('Ghost','Tune In, Turn On, Free Tibet')")
conn.execute("insert into records (artist_name, album_name) values('The Go-Betweens','16 Lovers Lane')")
conn.execute("insert into records (artist_name, album_name) values('Godspeed You! Black Emperor','F# A# (Infinity)')")
conn.execute("insert into records (artist_name, album_name) values('Godspeed You! Black Emperor','Slow Riot for New Zero Kanada')")
conn.execute("insert into records (artist_name, album_name) values('Godspeed You! Black Emperor','Lift Your Skinny Fists Like Antennas to Heaven')")
conn.execute("insert into records (artist_name, album_name) values('Godspeed You! Black Emperor','Yanqui U.X.O.')")
conn.execute("insert into records (artist_name, album_name) values('Godspeed You! Black Emperor','Allelujah! Don''t Bend! Ascend!')")
conn.execute("insert into records (artist_name, album_name) values('Godspeed You! Black Emperor','Asunder, Sweet And Other Distress''')")
conn.execute("insert into records (artist_name, album_name) values('Godspeed You! Black Emperor','""Luciferian Towers""')")
conn.execute("insert into records (artist_name, album_name) values('Gustav Holst - London Philharmonic Orchestra','The Planets')")
conn.execute("insert into records (artist_name, album_name) values('Hauschka','Abandoned City')")
conn.execute("insert into records (artist_name, album_name) values('Hello Saferide','Introducing... Hello Saferide')")
conn.execute("insert into records (artist_name, album_name) values('If These Trees Could Talk','If These Trees Could Talk')")
conn.execute("insert into records (artist_name, album_name) values('If These Trees Could Talk','Above the Earth, Below the Sky')")
conn.execute("insert into records (artist_name, album_name) values('If These Trees Could Talk','Red Forest')")
conn.execute("insert into records (artist_name, album_name) values('Iron & Wine','The Creek Drank the Cradle')")
conn.execute("insert into records (artist_name, album_name) values('James Iha','Be Strong Now')")
conn.execute("insert into records (artist_name, album_name) values('Jason Sharp','A Boat Upon Its Blood')")
conn.execute("insert into records (artist_name, album_name) values('Jerusalem in My Heart','Mo7it Al-Mo7it')")
conn.execute("insert into records (artist_name, album_name) values('The Jimi Hendrix Experience','Electric Ladyland')")
conn.execute("insert into records (artist_name, album_name) values('The Jimmy Chamberlin Complex','The Parable')")
conn.execute("insert into records (artist_name, album_name) values('Jon Mueller','Strung')")
conn.execute("insert into records (artist_name, album_name) values('Kaki King','Everybody Loves You')")
conn.execute("insert into records (artist_name, album_name) values('Kaki King','Pull Me Out Alive')")
conn.execute("insert into records (artist_name, album_name) values('Kaki King','Glow')")
conn.execute("insert into records (artist_name, album_name) values('Kikagaku Moyo','Forest of Lost Children')")
conn.execute("insert into records (artist_name, album_name) values('Kikagaku Moyo','House in the Tall Grass')")
conn.execute("insert into records (artist_name, album_name) values('Kikagaku Moyo','Masana Temples')")
conn.execute("insert into records (artist_name, album_name) values('The Killers','Hot Fuss')")
conn.execute("insert into records (artist_name, album_name) values('Kinski/Acid Mothers Temple','Kinski/Acid Mothers Temple')")
conn.execute("insert into records (artist_name, album_name) values('Kinski','Down Below It''s Chaos')")
conn.execute("insert into records (artist_name, album_name) values('Kinski','Cosy Moments')")
conn.execute("insert into records (artist_name, album_name) values('Kurt Vile','Bottle It In')")
conn.execute("insert into records (artist_name, album_name) values('L''Assassins','7pm Go!!!')")
conn.execute("insert into records (artist_name, album_name) values('Lee Ranaldo','Between the Times and the Tides')")
conn.execute("insert into records (artist_name, album_name) values('Lee Ranaldo and the Dust','Last Night on Earth')")
conn.execute("insert into records (artist_name, album_name) values('Lymbyc Systym','Love Your Abuser')")
conn.execute("insert into records (artist_name, album_name) values('Mason Williams','Them Poems and Things')")
conn.execute("insert into records (artist_name, album_name) values('Max Richter','The Blue Notebooks')")
conn.execute("insert into records (artist_name, album_name) values('Max Richter','Songs from Before')")
conn.execute("insert into records (artist_name, album_name) values('Max Richter','Infra')")
conn.execute("insert into records (artist_name, album_name) values('Max Richter','From Sleep')")
conn.execute("insert into records (artist_name, album_name) values('Michael Jackson','Off the Wall')")
conn.execute("insert into records (artist_name, album_name) values('Michael Jackson','Thriller')")
conn.execute("insert into records (artist_name, album_name) values('Michael Jackson','Bad')")
conn.execute("insert into records (artist_name, album_name) values('The Microphones','""The Glow"" Pt. 2')")
conn.execute("insert into records (artist_name, album_name) values('Minami Deutsch','With Dim Light')")
conn.execute("insert into records (artist_name, album_name) values('Minus the Bear','Highly Refined Pirates')")
conn.execute("insert into records (artist_name, album_name) values('Minus the Bear/City on Film','This Ain''t a Surfin'' Movie (remixed by IQU)/Pony''s Last Trick (remixed by Notebook)')")
conn.execute("insert into records (artist_name, album_name) values('Modest Mouse','We Were Dead Before the Ship Even Sank')")
conn.execute("insert into records (artist_name, album_name) values('Mogwai','Rock Action')")
conn.execute("insert into records (artist_name, album_name) values('Mogwai','Happy Songs For Happy People')")
conn.execute("insert into records (artist_name, album_name) values('Mogwai','Mr Beast')")
conn.execute("insert into records (artist_name, album_name) values('Mogwai','Rave Tapes')")
conn.execute("insert into records (artist_name, album_name) values('The Most Serene Republic/Headlights','Tradegy of the Commons/Put Us Back Together Right')")
conn.execute("insert into records (artist_name, album_name) values('The Mountain Goats and Kaki King','Black Pear Tree')")
conn.execute("insert into records (artist_name, album_name) values('Mount Eerie','Wind''s Poem')")
conn.execute("insert into records (artist_name, album_name) values('Nada Surf','Let Go')")
conn.execute("insert into records (artist_name, album_name) values('Nada Surf','The Weight Is a Gift')")
conn.execute("insert into records (artist_name, album_name) values('Neil Young & Crazy Horse','Everybody Knows This Is Nowhere')")
conn.execute("insert into records (artist_name, album_name) values('Neil Young','Harvest')")
conn.execute("insert into records (artist_name, album_name) values('Nick Drake','Five Leaves Left')")
conn.execute("insert into records (artist_name, album_name) values('Nick Drake','Bryter Layter')")
conn.execute("insert into records (artist_name, album_name) values('Nick Drake','Pink Moon')")
conn.execute("insert into records (artist_name, album_name) values('Oasis','Definitely Maybe')")
conn.execute("insert into records (artist_name, album_name) values('Pavement','Crooked Rain Crooked Rain')")
conn.execute("insert into records (artist_name, album_name) values('Pele','Elephant')")
conn.execute("insert into records (artist_name, album_name) values('A Perfect Circle','Weak and Powerless')")
conn.execute("insert into records (artist_name, album_name) values('Pixies','Surfer Rosa')")
conn.execute("insert into records (artist_name, album_name) values('The Police','Ghost in the Machine')")
conn.execute("insert into records (artist_name, album_name) values('Portico Quartet','Isla')")
conn.execute("insert into records (artist_name, album_name) values('Portico Quartet','Untitled (AITAOA #2)')")
conn.execute("insert into records (artist_name, album_name) values('Portico Quartet','Memory Streams')")
conn.execute("insert into records (artist_name, album_name) values('Primal Scream','Screamadelica')")
conn.execute("insert into records (artist_name, album_name) values('Prince','1999')")
conn.execute("insert into records (artist_name, album_name) values('Prince and the Revolution','Let''s Go Crazy')")
conn.execute("insert into records (artist_name, album_name) values('Radiohead','Kid A')")
conn.execute("insert into records (artist_name, album_name) values('Red Sparowes','Every Red Heart Shines Toward the Red Sun')")
conn.execute("insert into records (artist_name, album_name) values('Respira','This Is Not What You Had Planned')")
conn.execute("insert into records (artist_name, album_name) values('Robert Randolph & the Family Band','I Need More Love Remixes')")
conn.execute("insert into records (artist_name, album_name) values('Rogue Wave','Out of the Shadow')")
conn.execute("insert into records (artist_name, album_name) values('Rogue Wave','Descended Like Vultures')")
conn.execute("insert into records (artist_name, album_name) values('The Rosebuds','Loud Planes Fly Low')")
conn.execute("insert into records (artist_name, album_name) values('Russian Circles','Enter')")
conn.execute("insert into records (artist_name, album_name) values('Russian Circles','Upper Ninety')")
conn.execute("insert into records (artist_name, album_name) values('Russian Circles/These Arms Are Snakes','Philios/Camera Shy/Trix')")
conn.execute("insert into records (artist_name, album_name) values('Russian Circles','Geneva')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Heartbreaker')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Gold')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Demolition')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams & the Cardinals','Cold Roses')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams & the Cardinals','Jacksonville City Nights')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','29')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Oblivion')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Orion')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Valhalla')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams & the Cardinals','III/IV')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Ashes & Fire')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Come Home/Starsign')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Gimme Something Good')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Ryan Adams')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Adams','Prisoner')")
conn.execute("insert into records (artist_name, album_name) values('Ryan Teague','Block Boundaries')")
conn.execute("insert into records (artist_name, album_name) values('Saltland','I Thought It Was Us But It Was All of Us')")
conn.execute("insert into records (artist_name, album_name) values('The Shins','Chutes Too Narrow')")
conn.execute("insert into records (artist_name, album_name) values('The Silver Mt. Zion Memorial Orchestra & Tra-La-La Band','Born into Trouble as the Sparks Fly Upward')")
conn.execute("insert into records (artist_name, album_name) values('The Silver Mt. Zion Memorial Orchestra & Tra-La-La Band with Choir','""This Is Our Punk-Rock,"" Thee Rusted Satellites Gather + Sing,')")
conn.execute("insert into records (artist_name, album_name) values('Thee Silver Mountain Reveries','The ""Pretty Little Lightning Paw"" E.P.')")
conn.execute("insert into records (artist_name, album_name) values('Thee Silver Mt. Zion Memorial Orchestra & Tra-La-La Band','Horses in the Sky')")
conn.execute("insert into records (artist_name, album_name) values('Thee Silver Mt. Zion Memorial Orchestra & Tra-La-La Band','13 Blues for Thirteen Moons')")
conn.execute("insert into records (artist_name, album_name) values('Thee Silver Mt. Zion Memorial Orchestra','Kollaps Tradixionales')")
conn.execute("insert into records (artist_name, album_name) values('Thee Silver Mt. Zion Memorial Orchestra','""The West Will Rise Again"" E.P.')")
conn.execute("insert into records (artist_name, album_name) values('Thee Silver Mt. Zion Memorial Orchestra','Fuck Off Get Free We Pour Light on Everything')")
conn.execute("insert into records (artist_name, album_name) values('Thee Silver Mt. Zion Memorial Orchestra','Hang on to Each Other')")
conn.execute("insert into records (artist_name, album_name) values('Slint','Spiderland')")
conn.execute("insert into records (artist_name, album_name) values('Slowdive','Just For A Day')")
conn.execute("insert into records (artist_name, album_name) values('Slowdive','Pygmalion')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','Tristessa')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','Gish')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','Peel Sessions')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','I Am One')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','Siamese Dream')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','Today')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','Disarm')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','Pisces Iscariot')")
conn.execute("insert into records (artist_name, album_name) values('The Smashing Pumpkins','1979 Mixes')")
conn.execute("insert into records (artist_name, album_name) values('The Smashing Pumpkins','Mellon Collie and the Infinite Sadness')")
conn.execute("insert into records (artist_name, album_name) values('The Smashing Pumpkins','1979/Bullet with Butterfly Wings')")
conn.execute("insert into records (artist_name, album_name) values('The Smashing Pumpkins','Adore')")
conn.execute("insert into records (artist_name, album_name) values('The Smashing Pumpkins','Machina/the Machines of God')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','Tarantula')")
conn.execute("insert into records (artist_name, album_name) values('Smashing Pumpkins','That''s the Way (My Love Is)')")
conn.execute("insert into records (artist_name, album_name) values('The Smashing Pumpkins','The Aeroplane Flies High')")
conn.execute("insert into records (artist_name, album_name) values('Soft Verdict','Vergessen')")
conn.execute("insert into records (artist_name, album_name) values('Sonic Youth','Sister')")
conn.execute("insert into records (artist_name, album_name) values('Sonic Youth','Daydream Nation')")
conn.execute("insert into records (artist_name, album_name) values('Sonic Youth','A Thousand Leaves')")
conn.execute("insert into records (artist_name, album_name) values('Sonic Youth','Murray Street')")
conn.execute("insert into records (artist_name, album_name) values('Sonic Youth','Sonic Nurse')")
conn.execute("insert into records (artist_name, album_name) values('Sonic Youth','The Eternal')")
conn.execute("insert into records (artist_name, album_name) values('Sound Effects','Volume 1')")
conn.execute("insert into records (artist_name, album_name) values('Starchildren/Catherine','Delusions of Candor/Songs About Girls')")
conn.execute("insert into records (artist_name, album_name) values('Steve Reich','Music for 18 Musicians')")
conn.execute("insert into records (artist_name, album_name) values('Steve Reich','Octet/Music for a Large Ensemble/Violin Phase')")
conn.execute("insert into records (artist_name, album_name) values('Steve Reich','The Desert Music')")
conn.execute("insert into records (artist_name, album_name) values('Studio','West Coast')")
conn.execute("insert into records (artist_name, album_name) values('Talk Talk','Spirit of Eden')")
conn.execute("insert into records (artist_name, album_name) values('Tortoise','Millions Now Living Will Never Die')")
conn.execute("insert into records (artist_name, album_name) values('Unconditional Arms','Formation')")
conn.execute("insert into records (artist_name, album_name) values('Underworld','Two Months Off')")
conn.execute("insert into records (artist_name, album_name) values('Underworld','Barbara Barbara, We Face a Shining Future')")
conn.execute("insert into records (artist_name, album_name) values('Various Artists','20 Explosive Dynamic Super Smash Hit Explosions!')")
conn.execute("insert into records (artist_name, album_name) values('Various Artists','Percussion Music')")
conn.execute("insert into records (artist_name, album_name) values('VHS or Beta','Night on Fire')")
conn.execute("insert into records (artist_name, album_name) values('VHS or Beta','The Melting Moon')")
conn.execute("insert into records (artist_name, album_name) values('VHS or Beta','Bring on the Comets')")
conn.execute("insert into records (artist_name, album_name) values('Violent Femmes','The Blind Leading the Naked')")
conn.execute("insert into records (artist_name, album_name) values('Violent Femmes','American Music')")
conn.execute("insert into records (artist_name, album_name) values('Volcano Choir','Unmap')")
conn.execute("insert into records (artist_name, album_name) values('The Walkmen','Louisiana')")
conn.execute("insert into records (artist_name, album_name) values('Weekend','Jinx')")
conn.execute("insert into records (artist_name, album_name) values('Whiskeytown','Strangers Almanac')")
conn.execute("insert into records (artist_name, album_name) values('Whiskeytown','Pneumonia')")
conn.execute("insert into records (artist_name, album_name) values('The Wooden Birds','Two Matchsticks')")
conn.execute("insert into records (artist_name, album_name) values('Xylouris White','Goats')")
conn.execute("insert into records (artist_name, album_name) values('Yeasayer','Wait for the Summer')")
conn.execute("insert into records (artist_name, album_name) values('Zwan','Mary Star of the Sea')")
conn.commit()




conn.close()